# Generated by Django 2.2.6 on 2019-11-10 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.TextField()),
                ('fci_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('arrival_date', models.DateField()),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworkbackend.Breed')),
                ('caregiver', models.ManyToManyField(to='homeworkbackend.Caregiver')),
            ],
        ),
    ]
