# Generated by Django 2.2.6 on 2019-11-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkbackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='breed',
            new_name='breed_name',
        ),
    ]
